name: openvidu-test E2E

on: [push, workflow_dispatch]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: 'openvidu-test-e2e/docker/Dockerfile'
      options: '--privileged -p 4200:4200 -p 4443:4443 -p 4114:4114 -u root -e MY_UID=0 ' 
    steps:
       - name:  Build 1
         run: |
           cd openvidu/openvidu-browser
           npm install --quiet --unsafe-perm
           npm r un build --quiet
           npm pack --quiet
           cp openvidu-browser-*.tgz /opt/openvidu



