name: openvidu-test E2E

on: [push, workflow_dispatch]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2.3.4
       - name:  Build 1
         run: |
          cd openvidu-test-e2e/docker
          ls -lart
          docker build -t openvidu .
          docker run -i -t openvidu:latest
          ls -lart
          cd openvidu/openvidu-browser



