name: openvidu-test E2E

on: [push, workflow_dispatch]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2.3.4
       - name: Construcción de la Imagen openvidu-test-e2e
         run: |
          cd openvidu-test-e2e/docker
          docker build -t openvidu . 
       - name: Run image
         run: |
          docker run openvidu:latest --privileged -p 4200:4200 -p 4443:4443 -p 4114:4114 -u root -e MY_UID=0
          ls -lart
          cd openvidu/openvidu-browser
           



