name: openvidu-test E2E

on: [push, workflow_dispatch]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
       - name:  Build 1
         run: |
          docker build -t openvidu-test-e2e/docker
          docker run  -it openvidu-test-e2e/docker
          ls -lart
          cd openvidu/openvidu-browser



