name: openvidu-test E2E

on: [push, workflow_dispatch]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2.3.4
       - name: Construcción de la Imagen openvidu-test-e2e
         run: |
          cd openvidu-test-e2e/docker
          docker build -t openvidu .
       - name: Run image
         run: |
          docker run -i -t openvidu:latest
          ls -lart
          cd openvidu/openvidu-browser
           



